### ISSUE TITLE
Direct Install or need to activate it from Plugin Page

### ISSUE THREAD

**Issue by clementdes** [TheDMSGroup/mautic-segment-extras#2]
Hey Mate,
thank you for this realease. 
Could you just precise if I need to activate the plugin from the plugin page or not. 
If yes, Could you just mention the way it needs to be installed (FTP, change folder name, change other things...).
I am trying to set it up for my [SEO agency](http://punchify.me/seo/agence-seo.html), but can't figure out where the new functionalities appears (or are supposed to appear).
Thanks in advance

**Comment by scottshipman** [comment]
This works with mautic's plugin methodlogy. So, you can do the following:

1. Install by running composer require thedmsgroup/mautic-segment-extras-bundle
2. Go to /s/plugins/reload
3. Click "Segmnent Exxtras" and "Publish" the plugin.

**Comment by heathdutton** [comment]
Note, this could also be installed by unzipping it into your plugins folder, with the folder name "MauticSegmentExtrasBundle" and then going to /s/plugins/reload (if I'm not mistaken).

This plugin doesn't have any external dependencies, beyond Mautic.
